In [1]:
import pandas as pd
import numpy as np

In [2]:
f20 = pd.read_csv('cleaned_fifa_20.csv')

In [3]:
f20.head()

,Unnamed: 0,id,name,age,height,weight,nationality,club,rating,value_M,...,dribbling,defending,physic,heading,free_kick,ball_control,acceleration,speed,real_face_Yes,preferred_foot_Right
0,0,158023,L. Messi,32,170,72,Argentina,FC Barcelona,94,95.5,...,96.0,39.0,66.0,70,94,96,91,84,1,0
1,1,20801,Cristiano Ronaldo,34,187,83,Portugal,Juventus,93,58.5,...,89.0,35.0,78.0,89,76,92,89,91,1,1
2,2,190871,Neymar Jr,27,175,68,Brazil,Paris Saint-Germain,92,105.5,...,95.0,32.0,58.0,62,87,95,94,89,1,1
3,3,200389,J. Oblak,26,188,87,Slovenia,Atlético Madrid,91,77.5,...,NaN,NaN,NaN,15,14,30,43,60,1,1
4,4,183277,E. Hazard,28,175,74,Belgium,Real Madrid,91,90.0,...,94.0,35.0,66.0,61,79,94,94,88,1,1

In [4]:
f20 = f20.drop(columns='Unnamed: 0')

In [5]:
f20.shape

(18278, 27)

In [6]:
f20_young = f20.loc[f20['age'] < 26]

In [7]:
f20_young.age.max()

25

In [8]:
f20_young1 = f20_young.loc[f20_young['value_M'] <= 30.00]

In [9]:
f20_young1.value_M.max()

30.0

In [10]:
f20_young3 = f20_young1[f20_young1['rating'].between( 80, 91)]

In [11]:
f20_young3.rating.min()

80

In [12]:
f20_young3.rating.max()

83

In [13]:
f20_young3.shape

(92, 27)

In [14]:
f20_young3.head()

,id,name,age,height,weight,nationality,club,rating,value_M,wage_K,...,dribbling,defending,physic,heading,free_kick,ball_control,acceleration,speed,real_face_Yes,preferred_foot_Right
167,221087,Pau López,24,189,77,Spain,Roma,83,26.0,38.0,...,NaN,NaN,NaN,15,21,16,45,52,1,0
172,203574,J. Stones,25,188,70,England,Manchester City,83,30.0,140.0,...,72.0,84.0,77.0,83,29,80,65,71,1,1
174,210035,Grimaldo,23,171,69,Spain,SL Benfica,83,29.5,18.0,...,84.0,77.0,71.0,65,81,83,86,84,0,0
179,200458,L. Digne,25,178,74,France,Everton,83,28.5,97.0,...,79.0,80.0,76.0,71,83,83,79,78,1,0
181,204935,J. Pickford,25,185,77,England,Everton,83,24.0,78.0,...,NaN,NaN,NaN,15,16,40,53,44,1,0

In [15]:
f20_dream = f20_young3

In [16]:
f20_dream.shape

(92, 27)

In [17]:
f20_dream.position.value_counts()

CM    27
CB    15
ST    14
RM    11
GK     8
LB     6
LM     6
RB     5
Name: position, dtype: int64

In [18]:
f20_dream.head()

,id,name,age,height,weight,nationality,club,rating,value_M,wage_K,...,dribbling,defending,physic,heading,free_kick,ball_control,acceleration,speed,real_face_Yes,preferred_foot_Right
167,221087,Pau López,24,189,77,Spain,Roma,83,26.0,38.0,...,NaN,NaN,NaN,15,21,16,45,52,1,0
172,203574,J. Stones,25,188,70,England,Manchester City,83,30.0,140.0,...,72.0,84.0,77.0,83,29,80,65,71,1,1
174,210035,Grimaldo,23,171,69,Spain,SL Benfica,83,29.5,18.0,...,84.0,77.0,71.0,65,81,83,86,84,0,0
179,200458,L. Digne,25,178,74,France,Everton,83,28.5,97.0,...,79.0,80.0,76.0,71,83,83,79,78,1,0
181,204935,J. Pickford,25,185,77,England,Everton,83,24.0,78.0,...,NaN,NaN,NaN,15,16,40,53,44,1,0

In [19]:
#squad_433 = ['GK', 'LB', 'CB', 'CB', 'RB', 'LM', 'CDM', 'RM', 'LW', 'ST', 'RW']

In [20]:
#dream = []
#def dream(position):
    #f20_dream[f20_dream['position'].str.contains(position)].nlargest(3,'rating')
    #return dream

In [21]:
GK = f20_dream[f20_dream['position'].str.contains('GK')].nlargest(3,'rating')
LB = f20_dream[f20_dream['position'].str.contains('LB')].nlargest(3,'rating')
RB = f20_dream[f20_dream['position'].str.contains('RB')].nlargest(3,'rating')
CB = f20_dream[f20_dream['position'].str.contains('CB')].nlargest(6,'rating') #2x CB
LM = f20_dream[f20_dream['position'].str.contains('LM')].nlargest(3,'rating')
RM = f20_dream[f20_dream['position'].str.contains('RM')].nlargest(3,'rating')
CM = f20_dream[f20_dream['position'].str.contains('CM')].nlargest(3,'rating') 
ST = f20_dream[f20_dream['position'].str.contains('ST')].nlargest(9,'rating') #3x strikers
frames = (GK, LB, RB, CB, LM, RM, CM, ST)
dream_team = pd.concat(frames, axis=0, ignore_index=True)

In [22]:
dream_team[['name', 'position', 'preferred_foot', 'rating', 'nationality', 'club', 'value_M', 'wage_K']]

,name,position,preferred_foot,rating,nationality,club,value_M,wage_K
0,Pau López,GK,Left,83,Spain,Roma,26.0,38.0
1,J. Pickford,GK,Left,83,England,Everton,24.0,78.0
2,T. Strakosha,GK,Right,82,Albania,Lazio,22.0,39.0
3,Grimaldo,LB,Left,83,Spain,SL Benfica,29.5,18.0
4,L. Digne,LB,Left,83,France,Everton,28.5,97.0
5,Gayà,LB,Left,81,Spain,Valencia CF,21.0,35.0
6,Nélson Semedo,RB,Right,82,Portugal,FC Barcelona,26.0,150.0
7,Ricardo Pereira,RB,Right,82,Portugal,Leicester City,23.5,89.0
8,Héctor Bellerín,RB,Right,80,Spain,Arsenal,17.5,69.0
9,J. Stones,CB,Right,83,England,Manchester City,30.0,140.0
10,P. Kimpembe,CB,Left,82,France,Paris Saint-Germain,26.5,75.0
11,D. Rugani,CB,Right,82,Italy,Juventus,26.0,95.0
12,Éder Militão,CB,Right,81,Brazil,Real Madrid,23.0,105.0
13,V. Lindelöf,CB,Right,81,Sweden,Manchester United,22.0,97.0
14,M. Ginter,CB,Right,81,Germany,Borussia Mönchengladbach,19.5,33.0
15,David Neres,LM,Left,81,Brazil,Ajax,24.0,26.0
16,R. Fraser,LM,Right,81,Scotland,Bournemouth,21.5,76.0
17,R. Guerreiro,LM,Left,81,Portugal,Borussia Dortmund,21.5,79.0
18,S. Bergwijn,RM,Right,82,Netherlands,PSV,30.0,22.0
19,A. Correa,RM,Right,82,Argentina,Atlético Madrid,29.0,59.0
20,H. Lozano,RM,Right,82,Mexico,PSV,29.0,26.0
21,M. Kovačić,CM,Right,82,Croatia,Chelsea,29.0,125.0
22,N. Keïta,CM,Right,82,Guinea,Liverpool,29.0,95.0
23,L. Torreira,CM,Right,82,Uruguay,Arsenal,27.0,80.0
24,A. Belotti,ST,Right,82,Italy,Torino,30.0,63.0
25,Iñaki Williams,ST,Right,82,Spain,Athletic Club de Bilbao,29.0,36.0
26,L. Martínez,ST,Right,81,Argentina,Inter,27.0,61.0
27,Y. Poulsen,ST,Right,81,Denmark,RB Leipzig,22.0,65.0
28,João Félix,ST,Right,80,Portugal,Atlético Madrid,28.0,38.0
29,K. Piątek,ST,Right,80,Poland,Milan,20.5,44.0
30,Diogo Jota,ST,Right,80,Portugal,Wolverhampton Wanderers,20.5,84.0
31,M. Dembélé,ST,Right,80,France,Olympique Lyonnais,20.0,71.0
32,Santi Mina,ST,Right,80,Spain,RC Celta,20.0,29.0

In [23]:
GK_on = dream_team[dream_team['position'].str.contains('GK')].nlargest(1,'rating')
LB_on = dream_team[dream_team['position'].str.contains('LB')].nlargest(1,'rating')
RB_on = dream_team[dream_team['position'].str.contains('RB')].nlargest(1,'rating')
CB_on = dream_team[dream_team['position'].str.contains('CB')].nlargest(2,'rating') #2x CB
LM_on = dream_team[dream_team['position'].str.contains('LM')].nlargest(1,'rating')
RM_on = dream_team[dream_team['position'].str.contains('RM')].nlargest(1,'rating')
CM_on = dream_team[dream_team['position'].str.contains('CM')].nlargest(1,'rating') 
ST_on = dream_team[dream_team['position'].str.contains('ST')].nlargest(3,'rating') #3x strikers

In [24]:
frames_on = (GK_on, LB_on, RB_on, CB_on, LM_on, RM_on, CM_on, ST_on)
dream_team_on = pd.concat(frames_on, axis=0, ignore_index=True)

In [25]:
dream_team_on

,id,name,age,height,weight,nationality,club,rating,value_M,wage_K,...,dribbling,defending,physic,heading,free_kick,ball_control,acceleration,speed,real_face_Yes,preferred_foot_Right
0,221087,Pau López,24,189,77,Spain,Roma,83,26.0,38.0,...,NaN,NaN,NaN,15,21,16,45,52,1,0
1,210035,Grimaldo,23,171,69,Spain,SL Benfica,83,29.5,18.0,...,84.0,77.0,71.0,65,81,83,86,84,0,0
2,227928,Nélson Semedo,25,177,67,Portugal,FC Barcelona,82,26.0,150.0,...,81.0,77.0,75.0,58,30,80,91,92,0,1
3,203574,J. Stones,25,188,70,England,Manchester City,83,30.0,140.0,...,72.0,84.0,77.0,83,29,80,65,71,1,1
4,225850,P. Kimpembe,23,189,80,France,Paris Saint-Germain,82,26.5,75.0,...,67.0,81.0,83.0,79,32,78,73,77,1,0
5,236632,David Neres,22,175,66,Brazil,Ajax,81,24.0,26.0,...,87.0,36.0,65.0,45,52,86,88,87,0,0
6,225953,S. Bergwijn,21,178,78,Netherlands,PSV,82,30.0,22.0,...,85.0,40.0,73.0,60,66,85,88,89,0,1
7,207410,M. Kovačić,25,176,78,Croatia,Chelsea,82,29.0,125.0,...,86.0,67.0,70.0,42,68,89,79,73,1,1
8,208596,A. Belotti,25,181,72,Italy,Torino,82,30.0,63.0,...,77.0,41.0,82.0,84,56,75,77,77,1,1
9,216201,Iñaki Williams,25,186,79,Spain,Athletic Club de Bilbao,82,29.0,36.0,...,80.0,41.0,82.0,71,53,77,93,95,1,1
10,231478,L. Martínez,21,174,81,Argentina,Inter,81,27.0,61.0,...,82.0,40.0,83.0,82,33,82,81,81,0,1

In [26]:
dream_team_on[['name', 'position', 'rating', 'nationality', 'preferred_foot', 'club', 'value_M', 'wage_K']]

,name,position,rating,nationality,preferred_foot,club,value_M,wage_K
0,Pau López,GK,83,Spain,Left,Roma,26.0,38.0
1,Grimaldo,LB,83,Spain,Left,SL Benfica,29.5,18.0
2,Nélson Semedo,RB,82,Portugal,Right,FC Barcelona,26.0,150.0
3,J. Stones,CB,83,England,Right,Manchester City,30.0,140.0
4,P. Kimpembe,CB,82,France,Left,Paris Saint-Germain,26.5,75.0
5,David Neres,LM,81,Brazil,Left,Ajax,24.0,26.0
6,S. Bergwijn,RM,82,Netherlands,Right,PSV,30.0,22.0
7,M. Kovačić,CM,82,Croatia,Right,Chelsea,29.0,125.0
8,A. Belotti,ST,82,Italy,Right,Torino,30.0,63.0
9,Iñaki Williams,ST,82,Spain,Right,Athletic Club de Bilbao,29.0,36.0
10,L. Martínez,ST,81,Argentina,Right,Inter,27.0,61.0

In [27]:
print(dream_team['value_M'].sum())
print(dream_team_on['value_M'].sum())

822.0
307.0

In [28]:
dream_team

,id,name,age,height,weight,nationality,club,rating,value_M,wage_K,...,dribbling,defending,physic,heading,free_kick,ball_control,acceleration,speed,real_face_Yes,preferred_foot_Right
0,221087,Pau López,24,189,77,Spain,Roma,83,26.0,38.0,...,NaN,NaN,NaN,15,21,16,45,52,1,0
1,204935,J. Pickford,25,185,77,England,Everton,83,24.0,78.0,...,NaN,NaN,NaN,15,16,40,53,44,1,0
2,212151,T. Strakosha,24,193,78,Albania,Lazio,82,22.0,39.0,...,NaN,NaN,NaN,11,12,15,41,46,0,1
3,210035,Grimaldo,23,171,69,Spain,SL Benfica,83,29.5,18.0,...,84.0,77.0,71.0,65,81,83,86,84,0,0
4,200458,L. Digne,25,178,74,France,Everton,83,28.5,97.0,...,79.0,80.0,76.0,71,83,83,79,78,1,0
5,211688,Gayà,24,172,66,Spain,Valencia CF,81,21.0,35.0,...,80.0,75.0,69.0,52,49,81,83,87,1,0
6,227928,Nélson Semedo,25,177,67,Portugal,FC Barcelona,82,26.0,150.0,...,81.0,77.0,75.0,58,30,80,91,92,0,1
7,210243,Ricardo Pereira,25,175,70,Portugal,Leicester City,82,23.5,89.0,...,81.0,79.0,73.0,64,45,81,85,86,1,1
8,203747,Héctor Bellerín,24,178,74,Spain,Arsenal,80,17.5,69.0,...,78.0,76.0,66.0,60,50,78,94,90,1,1
9,203574,J. Stones,25,188,70,England,Manchester City,83,30.0,140.0,...,72.0,84.0,77.0,83,29,80,65,71,1,1
10,225850,P. Kimpembe,23,189,80,France,Paris Saint-Germain,82,26.5,75.0,...,67.0,81.0,83.0,79,32,78,73,77,1,0
11,211320,D. Rugani,24,190,84,Italy,Juventus,82,26.0,95.0,...,64.0,85.0,74.0,84,25,65,61,66,1,1
12,240130,Éder Militão,21,186,78,Brazil,Real Madrid,81,23.0,105.0,...,71.0,81.0,81.0,77,40,71,78,80,0,1
13,221660,V. Lindelöf,24,187,80,Sweden,Manchester United,81,22.0,97.0,...,72.0,82.0,78.0,79,59,76,72,76,1,1
14,207862,M. Ginter,25,191,89,Germany,Borussia Mönchengladbach,81,19.5,33.0,...,65.0,82.0,77.0,85,42,72,54,69,1,1
15,236632,David Neres,22,175,66,Brazil,Ajax,81,24.0,26.0,...,87.0,36.0,65.0,45,52,86,88,87,0,0
16,207807,R. Fraser,25,163,70,Scotland,Bournemouth,81,21.5,76.0,...,83.0,46.0,61.0,30,72,81,92,88,1,1
17,209889,R. Guerreiro,25,170,71,Portugal,Borussia Dortmund,81,21.5,79.0,...,85.0,66.0,57.0,37,82,85,80,68,1,0
18,225953,S. Bergwijn,21,178,78,Netherlands,PSV,82,30.0,22.0,...,85.0,40.0,73.0,60,66,85,88,89,0,1
19,214997,A. Correa,24,171,68,Argentina,Atlético Madrid,82,29.0,59.0,...,86.0,54.0,65.0,67,65,87,87,80,1,1
20,221992,H. Lozano,23,175,70,Mexico,PSV,82,29.0,26.0,...,83.0,41.0,66.0,58,65,81,94,93,1,1
21,207410,M. Kovačić,25,176,78,Croatia,Chelsea,82,29.0,125.0,...,86.0,67.0,70.0,42,68,89,79,73,1,1
22,220971,N. Keïta,24,172,64,Guinea,Liverpool,82,29.0,95.0,...,88.0,65.0,66.0,42,70,88,77,66,1,1
23,223959,L. Torreira,23,168,64,Uruguay,Arsenal,82,27.0,80.0,...,80.0,81.0,75.0,59,78,81,79,72,1,1
24,208596,A. Belotti,25,181,72,Italy,Torino,82,30.0,63.0,...,77.0,41.0,82.0,84,56,75,77,77,1,1
25,216201,Iñaki Williams,25,186,79,Spain,Athletic Club de Bilbao,82,29.0,36.0,...,80.0,41.0,82.0,71,53,77,93,95,1,1
26,231478,L. Martínez,21,174,81,Argentina,Inter,81,27.0,61.0,...,82.0,40.0,83.0,82,33,82,81,81,0,1
27,207791,Y. Poulsen,25,193,78,Denmark,RB Leipzig,81,22.0,65.0,...,75.0,56.0,82.0,85,43,76,81,84,1,1
28,242444,João Félix,19,181,70,Portugal,Atlético Madrid,80,28.0,38.0,...,81.0,40.0,70.0,69,58,80,79,85,0,1
29,223113,K. Piątek,24,183,77,Poland,Milan,80,20.5,44.0,...,73.0,38.0,71.0,80,40,76,78,75,0,1
30,224458,Diogo Jota,22,178,73,Portugal,Wolverhampton Wanderers,80,20.5,84.0,...,84.0,53.0,76.0,52,58,84,88,79,1,1
31,211591,M. Dembélé,22,183,74,France,Olympique Lyonnais,80,20.0,71.0,...,76.0,30.0,81.0,76,41,79,79,85,0,1
32,212623,Santi Mina,23,181,77,Spain,RC Celta,80,20.0,29.0,...,78.0,53.0,72.0,77,55,79,75,78,1,1

In [29]:
dream_team_on.to_csv('starting_11.csv')
dream_team.to_csv('dream_team_on_budget.csv')